---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet build -c Release
  - name: publish
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet publish -o /release-win-x64 -c Release --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true
      - dotnet publish -o /release-linux-x64 -c Release --self-contained --runtime linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true
      - mv /release-win-x64/OpenStreetMap.AddressParser.exe /release-win-x64/openstreetmap-addressparser-win64.exe
      - mv /release-linux-x64/OpenStreetMap.AddressParser /release-linux-x64/openstreetmap-addressparser-linux64
    when:
      event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_release_token
      files:
        - /release-win-x64/openstreetmap-addressparser-win64.exe
        - /release-linux-x64/openstreetmap-addressparser-linux64
    when:
      event: tag
      
